const CANVAS_HEIGHT = 600
const CANVAS_WIDTH = 800
const MONSTER_HEIGHT = 36
const MONSTER_WIDTH = 46
const PLAYER_HEIGHT = 64
const PLAYER_WIDTH = 64
const PLAYER_SPEED = 10
const SPAWN_RATE_IN_MS = 1000
const COUNTDOWN_IN_MS = 4000

export {
  CANVAS_HEIGHT,
  CANVAS_WIDTH,
  MONSTER_HEIGHT,
  MONSTER_WIDTH,
  PLAYER_HEIGHT,
  PLAYER_WIDTH,
  PLAYER_SPEED,
  SPAWN_RATE_IN_MS,
  COUNTDOWN_IN_MS
}

